name: Common Steps
description: Common steps for all workflows

defaults:
  run:
    shell: bash

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Git make safe.directory
      run: |
        git config --global --add safe.directory "*"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver: docker
        driver-opts: |
            network=host
