name: Common Steps
description: Common steps for all workflows

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    
    - name: Git make safe.directory
      run: |
        git config --global --add safe.directory "*"
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver: docker
        driver-opts: |
            network=host
