name: Common Steps

inputs:
  dockerhub_username:
    required: true
  dockerhub_access_token:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    
    - name: Git make safe.directory
      run: |
        git config --global --add safe.directory "*"
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_access_token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver: docker
        driver-opts: |
            network=host
